apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: simple-express
  name: simple-express
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: simple-express
    spec:
      containers:
      - image: rebekkahaley/simple-express
        name: simple-express
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always