apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-express
  labels:
    app: simple-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-express
  template:
    metadata:
      labels:
        app: simple-express
    spec:
      containers:
      - name: simple-api
        image: rebekkahaley/simple-express
        ports:
        - containerPort: 80